routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

// Route::get('/admin', function () {
//     return view('trips.index');
// });


// Route::resource('/trips', 'TripController');

Route::resource('/trips', 'TripController@index');

Route::get('/create', 'TripController@create');
Route::resource('trips', 'TripController');
Route::resource('user', 'UserController');




// <div class="row">
//     @foreach($trips as $index => $trip)
//         <div class="col-md-4">
//             <div class="l3photo-background">
//                 <img class="l3photo" src="{{ $trip->image }}" height="200" width="100%">
//                 @if (Auth::guest())
//                 @else
//                 <span class="l3price"><strike>{{ $trip->price }} €</strike> <strong>{{ $trip->price_discount }} €</strong></span>
//                 @endif
//                 <h3>{{ $trip->title }}</h3>
//                 <p>{{ $trip->description }}</p>
//             </div>
//             <br>
//         </div>
//         @if(++$index % 3 == 0)
//         </div><div class="row">
//         @endif
//     @endforeach
// </div>

app/Trip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Trip extends Model
{
    protected $fillable = [
    	'title',
    	'price',
    	'price_discount',
    	'image',
    	'description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('welcome');
    }
}

app/Http/Controllers/TripController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Trip;
use Auth;

class TripController extends Controller
{

      // nusako ka gales matyti neprisijunges vartotojas
    public function __construct(){
        $this->middleware('auth', ['except' => ['welcome']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $trips = \App\Trip::all();
        return view('trips.index', compact('trips'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('trips.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_trip = \App\Trip::create($request->all());

        return redirect()->route('trips.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $trip = \App\Trip::find($id);

        return view('trips.show', compact('trip'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $trip = \App\Trip::find($id);
        return view('trips.create', compact('trip'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $trip = \App\Trip::find($id)->update($request->all());

        return redirect()->route('trips.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $trip = \App\Trip::find($id)->delete();
        return redirect()->route('trips.index');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;

class UserController extends Controller
{
    public function __construct(){

        $this->middleware(function ($request, $next){
            if(\Auth::guest()
                ||
                (!\Auth::guest() && \Auth::user()->is_admin == 0))
            {
                return redirect()->route('login');
            }

            return $next($request);
        });
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = \App\User::all();
        // var_dump($users);
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $new_user = \App\User::create($request->all());

        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = \App\User::find($id);
        return view('user.create', compact('user'));;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // issaugom formos reiksmes, kad galetume modifkuoti
        $data = $request->all();
        
        if(!empty($request->password)){
            // jei password laukas nera tuscias - perrasom masyvo 'password' reiksme su jo pacio reiksme tik uzhashinta
            $data['password'] = \Hash::make($request->password);
        }else{
            // ismetam 'password' key is masyvo, nes kitaip uzsaugotu kaip tuscia password'a
            unset($data['password']);
        }
        
        // atnaujinam user duomenis su modifikuotais duomenimis
        $user = \App\User::find($id)->update($data);

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = \App\User::find($id)->delete();
        return redirect()->route('user.index');
    }
}

resources/views/home.blade.php
@extends('layout.main')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default logReg">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layout/main.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700&amp;subset=latin-ext" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ asset('css/styles.css') }}">
	<title>traveler</title>
</head>
<body>
	<div class="container">
		<header class="headerClass navigation">
			<div class="clearfix">
				<div class="logo">
					<a href="/traveler/public">
						<img src="{{ asset('logo/Logotipas.png') }}" height="100" width="130">
					</a>
				</div>
				<div>
					<nav>
						<ul>
							@if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Prisijunkti</a></li>
                            <li><a href="{{ url('/register') }}">Registruotis</a></li>
                        	@else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                       		 @endif

                       		
                       		@if ( Auth::check() && Auth::user()->is_admin == 1 )
								<li><a href="/traveler/public/trips" title="admin">administrator</a></li>
							@else	
                       		@endif
							<li><a href="/traveler/public#kontaktai" title="Kontaktai">Kontaktai</a></li>							
							<li><a href="/traveler/public#pasiulymai" title="Pasiūlymai">Pasiūlymai</a></li>
							<li><a href="/traveler/public#keliones" title="Kelionės">Kelionės</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	</div>

	<div class="container">
		@yield('content')
	</div>
	
	<div class="container">
		<footer id="kontaktai">
			<div class="row footeR">
				<div class="col-md-2"></div>
				<div class="col-md-2">
					<div class="">
						<h2>Kontaktai</h2>
						<p>Švitrigailos g. 8, LT-03127, Vilnius </p>
						<p>Tel.: (8 5) 888 9999</p>
						<p>El.p.: info@traveler.com</p>
					</div>
				</div>
				<div class="col-md-1"></div>
				<div class="col-md-2">
					<div class="">
						<h2>Sekite mus:</h2>
						<a href="https://facebook.com" target="_blank"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>
						<a href="https://twitter.com " target="_blank"><i class="fa fa-twitter-square" aria-hidden="true"></i></a>
						<a href="https://instagram.com" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
						<a href="https://linkedin.com" target="_blank"><i class="fa fa-linkedin-square" aria-hidden="true"></i></a>
					</div>
				</div>
				<div class="col-md-1"></div>
				<div class="col-md-2">
					<div class="">
						<h2>Mus rasite:</h2>
						<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2306.73412073999!2d25.265054215308073!3d54.679107981748956!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46dd9472c09e8bb1%3A0x8d2b9e6b4a1aa84f!2s%C5%A0vitrigailos+g.+8%2C+Vilnius+03223!5e0!3m2!1slt!2slt!4v1480351336497" width="270" height="220" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
				</div>
				<div class="col-md-2"></div>
			</div>
            <div class="coppyright">
            <hr>
                <h6>&#xA9; 2001-2016 UAB "traveler". Visos teisės saugomos.</h6> 
            </div>
		</footer>
	</div>	
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ url('/login') }}">Login</a></li>
                            <li><a href="{{ url('/register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ url('/logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>

resources/views/trips/create.blade.php
@extends('layout.main')
@section("content")
<div class="forms">
    <h3>{{ isset($trip) ? 'Edit trip' : 'Add trip' }}</h3>
    @if(isset($trip))
        {{ Form::open(['route' => ['trips.update', $trip->id], 'method' => "POST"]) }}
        {{ Form::hidden('_method', 'PUT') }}
    @else
        {{ Form::open(['route' => 'trips.store', 'method' => "POST"]) }}
    @endif
    {{ csrf_field() }}

        {{ Form::label('title', 'Title')}}
        @if(isset($trip))
            {{ Form::text('title', ($trip['title']), ['class' => 'form-control']) }}
        @else
            {{ Form::text('title', '', ['class' => 'form-control']) }}
        @endif

        {{ Form::label('price', 'Price') }}
        @if(isset($trip))
            {{ Form::text('price', ($trip['price']), ['class' => 'form-control']) }}
        @else
            {{ Form::text('price', '', ['class' => 'form-control']) }}
        @endif

        {{ Form::label('price_discount', 'Price_discount') }}
        @if(isset($trip))
            {{ Form::text('price_discount', ($trip['price_discount']), ['class' => 'form-control']) }}
        @else
            {{ Form::text('price_discount', '', ['class' => 'form-control']) }}
        @endif

        {{ Form::label('image', 'Image URL') }}
        @if(isset($trip))
            {{ Form::text('image', ($trip['image']), ['class' => 'form-control']) }}
        @else
            {{ Form::text('image', '', ['class' => 'form-control']) }}
        @endif

        {{ Form::label('description', 'Description') }}
        @if(isset($trip))
            {{ Form::textarea('description', ($trip['description']), ['class' => 'form-control']) }}
        @else
            {{ Form::textarea('description', '', ['class' => 'form-control']) }}
        @endif
        <br>
    @if(isset($trip))
        {{ Form::submit('Edit trip', ['class' => 'btn btn-primary']) }}
    @else
        {{ Form::submit('Add trip', ['class' => 'btn btn-primary']) }}
    @endif

    {{ Form::close() }}
    <br>
    @if(isset($trip))
        {{ Form::open(['route' => ['trips.destroy', $trip->id], 'method' => "POST"]) }}
        {{ Form::hidden('_method', 'DELETE') }}
                {{ csrf_field() }}
            {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}    
    @endif
    {{ Form::close() }}
</div>
@endsection

resources/views/trips/index.blade.php
@extends('layout.main')
@section ('content')
    <div class="forms">
        <div id="" class="layer3">
            <div>
                <h1>Pasiūlymai</h1>
                <a class="btn btn-warning" href="/traveler/public/user">Users menus</a>
                <br>
                <br>
                <a class="btn btn-warning" href="/traveler/public/create">Create trip</a>
            </div>
            <br>
                <div class="row">
                    @foreach($trips as $index => $trip)
                        <div class="col-md-4">
                            <div class="l3photo-background">
                                <img class="l3photo" src="{{ $trip->image }}" height="200" width="100%">
                                @if (Auth::guest())
                                @else
                                <span class="l3price"><strike>{{ $trip->price }} €</strike> <strong>{{ $trip->price_discount }} €</strong></span>
                                @endif
                                <h3>{{ $trip->title }}</h3>
                                <p>{{ $trip->description }}</p>
                            </div>
                            <div class="indexx">
                                <a class="btn btn-warning" href="{{ route('trips.edit', $trip->id) }}">EDIT</a>
                                <a class="btn btn-warning" href="{{ route('trips.show', $trip->id) }}">READ MORE</a>
                            </div>
                            <br>
                        </div>
                        @if(++$index % 3 == 0)
                        </div><div class="row">
                        @endif
                    @endforeach
                </div>
            <br>
        </div>
    </div>
@endsection

resources/views/trips/show.blade.php
@extends('layout.main')

@section('content')

<div class="row logReg">
    <div class="col-md-4">
        <div class="l3photo-background">
            <img class="l3photo" src="{{ $trip->image }}" height="200" width="100%">
            @if (Auth::guest())
            @else
            <span class="l3price"><strike>{{ $trip->price }} €</strike> <strong>{{ $trip->price_discount }} €</strong></span>
            @endif
            <h3>{{ $trip->title }}</h3>
            <p>{{ $trip->description }}</p>
        </div>
    </div>

@endsection

resources/views/user/create.blade.php
@extends("layout.main")
@section("content")
<div class="forms">
    <h3>{{ isset($user) ? 'Edit user' : 'Add user' }}</h3>
    @if(isset($user))
        {{ Form::open(['route' => ['user.update', $user->id], 'method' => "POST"]) }}
        {{ Form::hidden('_method', 'PUT') }}
    @else
        {{ Form::open(['route' => 'user.store', 'method' => "POST"]) }}
    @endif
    {{ csrf_field() }}
        {{ Form::label('name') }}
        @if(isset($user))
            {{ Form::text('name', ($user['name']), ['class' => 'form-control']) }}
        @else
            {{ Form::text('name', '', ['class' => 'form-control']) }}
        @endif
        {{ Form::label('Email') }}
        @if(isset($user))
            {{ Form::text('email', ($user['email']), ['class' => 'form-control']) }}
        @else
            {{ Form::text('email', '', ['class' => 'form-control']) }}
        @endif
        {{ Form::label('password') }}
        {{ Form::text('password', '', ['class' => 'form-control']) }}
        {{ Form::label('confirm password') }}
        {{ Form::text('confirm_password', '', ['class' => 'form-control']) }}
        {{ Form::label('') }}
        @if(isset($user))
            {{ Form::label('is_admin', "Is admin?") }}
            {{ Form::hidden("is_admin", 0) }}
            {{ Form::checkbox('is_admin', 1, $user->is_admin) }}
        @else
            {{ Form::label('is_admin', "Is admin?") }}
            {{ Form::hidden("is_admin", 0) }}
            {{ Form::checkbox('is_admin', 1, 0) }}
        @endif
        <br>



    @if(isset($user))
        {{ Form::submit('Edit user', ['class' => 'btn btn-primary']) }}
    @else
        {{ Form::submit('Add user', ['class' => 'btn btn-primary']) }}
    @endif
    {{ Form::close() }}
    <br>
    @if(isset($user))
        {{ Form::open(['route' => ['user.destroy', $user->id], 'method' => "POST"]) }}
        {{ Form::hidden('_method', 'DELETE') }}
                {{ csrf_field() }}
            {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
        
    @endif
    {{ Form::close() }}
</div>
@endsection

resources/views/user/index.blade.php
@extends('layout.main')

@section('content')
<div class="container forms">
	<h2>VARTOTOJAI</h2>

	@foreach($users as $user)
		<div class="col-md-12">
			<ul>
				<li>User name: {{ $user->name }}</li>
				<li>User email: {{ $user->email }}</li>
				<li>Admin = 1; Simple user = 0</li>
				{{ $user->is_admin }}
				<br>
				<a href="{{ route('user.edit', $user->id) }}">EDIT user</a>
			</ul>
		</div>
	@endforeach
</div>
@endsection